feature_order = [ 'consumption_UES_lag_1', 'consumption_UES_lag_2', 'consumption_UES_lag_3',
                 'consumption_UES_lag_4', 'consumption_UES_lag_5', 'consumption_UES_lag_6', 'consumption_UES_lag_7',
                 'consumption_UES_lag_8', 'consumption_UES_lag_9', 'consumption_UES_lag_10', 'consumption_UES_lag_11',
                 'consumption_UES_lag_12', 'consumption_UES_lag_13', 'consumption_UES_lag_14', 'consumption_UES_lag_15',
                 'consumption_UES_lag_16', 'consumption_UES_lag_17', 'consumption_UES_lag_18', 'consumption_UES_lag_19',
                 'consumption_UES_lag_20', 'consumption_UES_lag_21', 'consumption_UES_lag_22', 'consumption_UES_lag_23',
                 'consumption_UES_lag_24', 'consumption_UES_lag_25', 'consumption_UES_lag_26', 'consumption_UES_lag_27',
                 'consumption_UES_lag_28', 'consumption_UES_lag_29', 'consumption_UES_lag_30', 'temp_UES_lag_1',
                 'temp_UES_lag_2', 'temp_UES_lag_3', 'temp_UES_lag_4', 'temp_UES_lag_5', 'temp_UES_lag_6',
                 'temp_UES_lag_7', 'temp_UES_lag_8', 'temp_UES_lag_9', 'temp_UES_lag_10', 'temp_UES_lag_11',
                 'temp_UES_lag_12', 'temp_UES_lag_13', 'temp_UES_lag_14', 'temp_UES_lag_15', 'temp_UES_lag_16',
                 'temp_UES_lag_17', 'temp_UES_lag_18', 'temp_UES_lag_19', 'temp_UES_lag_20', 'temp_UES_lag_21',
                 'temp_UES_lag_22', 'temp_UES_lag_23', 'temp_UES_lag_24', 'temp_UES_lag_25', 'temp_UES_lag_26',
                 'temp_UES_lag_27', 'temp_UES_lag_28', 'temp_UES_lag_29', 'temp_UES_lag_30', 'consumption_NW_UES_lag_1',
                 'consumption_NW_UES_lag_2', 'consumption_NW_UES_lag_3', 'consumption_NW_UES_lag_4',
                 'consumption_NW_UES_lag_5', 'consumption_NW_UES_lag_6', 'consumption_NW_UES_lag_7',
                 'consumption_NW_UES_lag_8', 'consumption_NW_UES_lag_9', 'consumption_NW_UES_lag_10',
                 'consumption_NW_UES_lag_11', 'consumption_NW_UES_lag_12', 'consumption_NW_UES_lag_13',
                 'consumption_NW_UES_lag_14', 'consumption_NW_UES_lag_15', 'consumption_NW_UES_lag_16',
                 'consumption_NW_UES_lag_17', 'consumption_NW_UES_lag_18', 'consumption_NW_UES_lag_19',
                 'consumption_NW_UES_lag_20', 'consumption_NW_UES_lag_21', 'consumption_NW_UES_lag_22',
                 'consumption_NW_UES_lag_23', 'consumption_NW_UES_lag_24', 'consumption_NW_UES_lag_25',
                 'consumption_NW_UES_lag_26', 'consumption_NW_UES_lag_27', 'consumption_NW_UES_lag_28',
                 'consumption_NW_UES_lag_29', 'consumption_NW_UES_lag_30', 'temp_NW_lag_1', 'temp_NW_lag_2',
                 'temp_NW_lag_3', 'temp_NW_lag_4', 'temp_NW_lag_5', 'temp_NW_lag_6',
                 'temp_NW_lag_7', 'temp_NW_lag_8', 'temp_NW_lag_9', 'temp_NW_lag_10',
                 'temp_NW_lag_11', 'temp_NW_lag_12', 'temp_NW_lag_13', 'temp_NW_lag_14',
                 'temp_NW_lag_15', 'temp_NW_lag_16', 'temp_NW_lag_17', 'temp_NW_lag_18',
                 'temp_NW_lag_19', 'temp_NW_lag_20', 'temp_NW_lag_21', 'temp_NW_lag_22',
                 'temp_NW_lag_23', 'temp_NW_lag_24', 'temp_NW_lag_25', 'temp_NW_lag_26',
                 'temp_NW_lag_27', 'temp_NW_lag_28', 'temp_NW_lag_29', 'temp_NW_lag_30',
                 'temp_SPB_lag_1', 'temp_SPB_lag_2', 'temp_SPB_lag_3', 'temp_SPB_lag_4', 'temp_SPB_lag_5',
                 'temp_SPB_lag_6', 'temp_SPB_lag_7', 'temp_SPB_lag_8', 'temp_SPB_lag_9', 'temp_SPB_lag_10',
                 'temp_SPB_lag_11', 'temp_SPB_lag_12', 'temp_SPB_lag_13', 'temp_SPB_lag_14', 'temp_SPB_lag_15',
                 'temp_SPB_lag_16', 'temp_SPB_lag_17', 'temp_SPB_lag_18', 'temp_SPB_lag_19', 'temp_SPB_lag_20',
                 'temp_SPB_lag_21', 'temp_SPB_lag_22', 'temp_SPB_lag_23', 'temp_SPB_lag_24', 'temp_SPB_lag_25',
                 'temp_SPB_lag_26', 'temp_SPB_lag_27', 'temp_SPB_lag_28', 'temp_SPB_lag_29', 'temp_SPB_lag_30',
                 'pressure_SPB_lag_1', 'pressure_SPB_lag_2', 'pressure_SPB_lag_3', 'pressure_SPB_lag_4',
                 'pressure_SPB_lag_5', 'pressure_SPB_lag_6', 'pressure_SPB_lag_7', 'pressure_SPB_lag_8',
                 'pressure_SPB_lag_9', 'pressure_SPB_lag_10', 'pressure_SPB_lag_11', 'pressure_SPB_lag_12',
                 'pressure_SPB_lag_13', 'pressure_SPB_lag_14', 'pressure_SPB_lag_15', 'pressure_SPB_lag_16',
                 'pressure_SPB_lag_17', 'pressure_SPB_lag_18', 'pressure_SPB_lag_19', 'pressure_SPB_lag_20',
                 'pressure_SPB_lag_21', 'pressure_SPB_lag_22', 'pressure_SPB_lag_23', 'pressure_SPB_lag_24',
                 'pressure_SPB_lag_25', 'pressure_SPB_lag_26', 'pressure_SPB_lag_27', 'pressure_SPB_lag_28',
                 'pressure_SPB_lag_29', 'pressure_SPB_lag_30', 'humidity_SPB_lag_1', 'humidity_SPB_lag_2',
                 'humidity_SPB_lag_3', 'humidity_SPB_lag_4', 'humidity_SPB_lag_5', 'humidity_SPB_lag_6',
                 'humidity_SPB_lag_7', 'humidity_SPB_lag_8', 'humidity_SPB_lag_9', 'humidity_SPB_lag_10',
                 'humidity_SPB_lag_11', 'humidity_SPB_lag_12', 'humidity_SPB_lag_13', 'humidity_SPB_lag_14',
                 'humidity_SPB_lag_15', 'humidity_SPB_lag_16', 'humidity_SPB_lag_17', 'humidity_SPB_lag_18',
                 'humidity_SPB_lag_19', 'humidity_SPB_lag_20', 'humidity_SPB_lag_21', 'humidity_SPB_lag_22',
                 'humidity_SPB_lag_23', 'humidity_SPB_lag_24', 'humidity_SPB_lag_25', 'humidity_SPB_lag_26',
                 'humidity_SPB_lag_27', 'humidity_SPB_lag_28', 'humidity_SPB_lag_29', 'humidity_SPB_lag_30',
                 'wind_speed_SPB_lag_1', 'wind_speed_SPB_lag_2', 'wind_speed_SPB_lag_3', 'wind_speed_SPB_lag_4',
                 'wind_speed_SPB_lag_5', 'wind_speed_SPB_lag_6', 'wind_speed_SPB_lag_7', 'wind_speed_SPB_lag_8',
                 'wind_speed_SPB_lag_9', 'wind_speed_SPB_lag_10', 'wind_speed_SPB_lag_11', 'wind_speed_SPB_lag_12',
                 'wind_speed_SPB_lag_13', 'wind_speed_SPB_lag_14', 'wind_speed_SPB_lag_15', 'wind_speed_SPB_lag_16',
                 'wind_speed_SPB_lag_17', 'wind_speed_SPB_lag_18', 'wind_speed_SPB_lag_19', 'wind_speed_SPB_lag_20',
                 'wind_speed_SPB_lag_21', 'wind_speed_SPB_lag_22', 'wind_speed_SPB_lag_23', 'wind_speed_SPB_lag_24',
                 'wind_speed_SPB_lag_25', 'wind_speed_SPB_lag_26', 'wind_speed_SPB_lag_27', 'wind_speed_SPB_lag_28',
                 'wind_speed_SPB_lag_29', 'wind_speed_SPB_lag_30', 'cloudiness_SPB_lag_1', 'cloudiness_SPB_lag_2',
                 'cloudiness_SPB_lag_3', 'cloudiness_SPB_lag_4', 'cloudiness_SPB_lag_5', 'cloudiness_SPB_lag_6',
                 'cloudiness_SPB_lag_7', 'cloudiness_SPB_lag_8', 'cloudiness_SPB_lag_9', 'cloudiness_SPB_lag_10',
                 'cloudiness_SPB_lag_11', 'cloudiness_SPB_lag_12', 'cloudiness_SPB_lag_13', 'cloudiness_SPB_lag_14',
                 'cloudiness_SPB_lag_15', 'cloudiness_SPB_lag_16', 'cloudiness_SPB_lag_17', 'cloudiness_SPB_lag_18',
                 'cloudiness_SPB_lag_19', 'cloudiness_SPB_lag_20', 'cloudiness_SPB_lag_21', 'cloudiness_SPB_lag_22',
                 'cloudiness_SPB_lag_23', 'cloudiness_SPB_lag_24', 'cloudiness_SPB_lag_25', 'cloudiness_SPB_lag_26',
                 'cloudiness_SPB_lag_27', 'cloudiness_SPB_lag_28', 'cloudiness_SPB_lag_29', 'cloudiness_SPB_lag_30',
                 'USD_to_RUB_lag_1', 'USD_to_RUB_lag_2', 'USD_to_RUB_lag_3', 'USD_to_RUB_lag_4', 'USD_to_RUB_lag_5',
                 'USD_to_RUB_lag_6', 'USD_to_RUB_lag_7', 'USD_to_RUB_lag_8', 'USD_to_RUB_lag_9', 'USD_to_RUB_lag_10',
                 'USD_to_RUB_lag_11', 'USD_to_RUB_lag_12', 'USD_to_RUB_lag_13', 'USD_to_RUB_lag_14',
                 'USD_to_RUB_lag_15', 'USD_to_RUB_lag_16', 'USD_to_RUB_lag_17', 'USD_to_RUB_lag_18',
                 'USD_to_RUB_lag_19', 'USD_to_RUB_lag_20', 'USD_to_RUB_lag_21', 'USD_to_RUB_lag_22',
                 'USD_to_RUB_lag_23', 'USD_to_RUB_lag_24', 'USD_to_RUB_lag_25', 'USD_to_RUB_lag_26',
                 'USD_to_RUB_lag_27', 'USD_to_RUB_lag_28', 'USD_to_RUB_lag_29', 'USD_to_RUB_lag_30',
                 'gas_avg_price_lag_1', 'gas_avg_price_lag_2', 'gas_avg_price_lag_3', 'gas_avg_price_lag_4',
                 'gas_avg_price_lag_5', 'gas_avg_price_lag_6', 'gas_avg_price_lag_7', 'gas_avg_price_lag_8',
                 'gas_avg_price_lag_9', 'gas_avg_price_lag_10', 'gas_avg_price_lag_11', 'gas_avg_price_lag_12',
                 'gas_avg_price_lag_13', 'gas_avg_price_lag_14', 'gas_avg_price_lag_15', 'gas_avg_price_lag_16',
                 'gas_avg_price_lag_17', 'gas_avg_price_lag_18', 'gas_avg_price_lag_19', 'gas_avg_price_lag_20',
                 'gas_avg_price_lag_21', 'gas_avg_price_lag_22', 'gas_avg_price_lag_23', 'gas_avg_price_lag_24',
                 'gas_avg_price_lag_25', 'gas_avg_price_lag_26', 'gas_avg_price_lag_27', 'gas_avg_price_lag_28',
                 'gas_avg_price_lag_29', 'gas_avg_price_lag_30', 'oil_avg_price_lag_1', 'oil_avg_price_lag_2',
                 'oil_avg_price_lag_3', 'oil_avg_price_lag_4', 'oil_avg_price_lag_5', 'oil_avg_price_lag_6',
                 'oil_avg_price_lag_7', 'oil_avg_price_lag_8', 'oil_avg_price_lag_9', 'oil_avg_price_lag_10',
                 'oil_avg_price_lag_11', 'oil_avg_price_lag_12', 'oil_avg_price_lag_13', 'oil_avg_price_lag_14',
                 'oil_avg_price_lag_15', 'oil_avg_price_lag_16', 'oil_avg_price_lag_17', 'oil_avg_price_lag_18',
                 'oil_avg_price_lag_19', 'oil_avg_price_lag_20', 'oil_avg_price_lag_21', 'oil_avg_price_lag_22',
                 'oil_avg_price_lag_23', 'oil_avg_price_lag_24', 'oil_avg_price_lag_25', 'oil_avg_price_lag_26',
                 'oil_avg_price_lag_27', 'oil_avg_price_lag_28', 'oil_avg_price_lag_29', 'oil_avg_price_lag_30', 'year',
                 'month', 'day', 'dayofweek', 'consumption_UES_rm', 'consumption_NW_rm']
